### ISSUE TITLE
Where do you put the API Public key to make the token?

### ISSUE THREAD

**Issue by mikeacre** [epay3/epay3.Sdk#14]
There is no mention of the API public key at all in the demo, Yet I am getting a 401 error without. How do I load the Public key?

**Comment by mikeacre** [comment]
Ok I looked at the code and found:
function postToken(postUrl, publicKey, impersonationAccountKey, postTokenRequestModel)

I  put in a request to update this sample code specifying the variables for the post token function.

I still however am getting a 401 error.

**Comment by rhamilton281** [comment]
Apologies for the lack of response.  I'm going to close this issue due to its age.
